deployment:
tasks:
- export DEPLOYPATH=/home/contelexp/public_html/
# - /bin/cp Post1.html $DEPLOYPATH
# - /bin/cp index.html $DEPLOYPATH
# - /bin/rm -Rf $DEPLOYPATH
# - /bin/mkdir $DEPLOYPATH
- /bin/cp * $DEPLOYPATH
