<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Contel Experiencias</title>
    <!-- Font Awesome -->
<link
href="css/all.min.css" rel="stylesheet"/>
<!-- Google Fonts -->
<link
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
rel="stylesheet"
/>
<!-- MDB -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="css/bootstrap.min.css" >
    <!-- <link rel="stylesheet" href="assets/css/bootstrap.css"> -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:200,300,400,500&display=swap" rel="stylesheet">
    <link href="css/free-v4-font-face.min.css" rel="stylesheet">
    <link href="css/free-v4-shims.min.css" rel="stylesheet">
    <link href="css/free.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/estilos.css">
    <link rel="stylesheet" href="assets/css/font-awesome.min.css">

    <!-- Main CSS -->
    
    <link rel="stylesheet" href="assets/css/style.css">

   
</head>

<body>
    <header class="header-section d-lg-block d-none">
        <!-- Start Bottom Area -->
        <div class="header-bottom sticky-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <!-- Header Main Menu -->
                        <div class="main-menu">
                            <nav style="float: right;">
                                <ul>
                                    <li>
                                        <a href="index.html">Inicio</a>
                                    </li>
                                    <li>
                                        <a href="index.html">Blog</a>
                                    </li>
                          
                                </ul>
                            </nav>
                        </div> <!-- Header Main Menu Start -->
                    </div>
                </div>
            </div>
        </div> <!-- End Bottom Area -->
    </header> <!-- ...:::: End Header Section:::... -->

    <!-- ...:::: Start Mobile Header Section:::... -->
    <div class="mobile-header-section d-block d-lg-none">
        <!-- Start Mobile Header Wrapper -->
        <div class="mobile-header-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-12 d-flex justify-content-between align-items-center">
                        <div class="mobile-header--left">
                            <a href="" class="mobile-logo-link">
                                <img  class="d-block" width="42" height="42"  src="img/Logos/Contel-Experiencias-B.png" alt="">    
                                <!-- <svg class="d-block" width="42" height="42" viewBox="0 0 612 612" xmlns="http://www.w3.org/2000/svg" focusable="false"><title>Bootstrap</title><path fill="currentColor" d="M510 8a94.3 94.3 0 0 1 94 94v408a94.3 94.3 0 0 1-94 94H102a94.3 94.3 0 0 1-94-94V102a94.3 94.3 0 0 1 94-94h408m0-8H102C45.9 0 0 45.9 0 102v408c0 56.1 45.9 102 102 102h408c56.1 0 102-45.9 102-102V102C612 45.9 566.1 0 510 0z"></path><path fill="currentColor" d="M196.77 471.5V154.43h124.15c54.27 0 91 31.64 91 79.1 0 33-24.17 63.72-54.71 69.21v1.76c43.07 5.49 70.75 35.82 70.75 78 0 55.81-40 89-107.45 89zm39.55-180.4h63.28c46.8 0 72.29-18.68 72.29-53 0-31.42-21.53-48.78-60-48.78h-75.57zm78.22 145.46c47.68 0 72.73-19.34 72.73-56s-25.93-55.37-76.46-55.37h-74.49v111.4z"></path></svg> -->
                            </a>
                        </div>
                        <div class="mobile-header--right">
                            <a href="#mobile-menu-offcanvas" class="mobile-menu offcanvas-toggle">
                                <span class="mobile-menu-dash"></span>
                                <span class="mobile-menu-dash"></span>
                                <span class="mobile-menu-dash"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- End Mobile Header Wrapper -->
    </div> <!-- ...:::: Start Mobile Header Section:::... -->

    <!-- ...:::: Start Offcanvas Mobile Menu Section:::... -->
    <div id="mobile-menu-offcanvas" class="offcanvas offcanvas-leftside offcanvas-mobile-menu-section">
        <!-- Start Offcanvas Header -->
        <div class="offcanvas-header text-right">
            <button class="offcanvas-close"><i class="fa fa-times"></i></button>
        </div> <!-- End Offcanvas Header -->
        <!-- Start Offcanvas Mobile Menu Wrapper -->
        <div class="offcanvas-mobile-menu-wrapper">
            <!-- Start Mobile Menu User Top -->
            <div class="mobile-menu-top">
                <span>Contel Experiencias</span>
            </div> <!-- End Mobile Menu User Top -->
            <!-- Start Mobile Menu Center -->
            <div class="mobile-menu-center">
                <!-- Start Mobile Menu Nav -->
                <div class="offcanvas-menu">
                    <ul>
                        <li>
                            <a href="#"><span>Inicio</span></a>
                          
                        </li>
                        
                        <li>
                            <a href="#"><span>Blogs</span></a>
                           
                        </li>
                    
                    </ul>
                </div> <!-- End Mobile Menu Nav -->

               
            </div> <!-- End Mobile Menu Center -->
			<!-- Start Mobile Menu  Bottom -->
            <div class="mobile-menu-bottom">
                 <!-- Mobile Manu Mail Address -->
                <a class="mobile-menu-email icon-text-right" href=""><img style= " width: 6%;"src="img/Logos/email.png" alt=""><i class="fa"> promociones@contelexperiencias.com</i></a>

                <!-- Mobile Manu Social Link -->
                <ul class="mobile-menu-social">
                    <li><a href="https://www.facebook.com/ContelExperiencias"><img style= " width: 70%;"src="img/Logos/face.png" alt=""></a></li>
                    <li><a href="https://www.instagram.com/contelexperiencias/" class=""><img style= " width: 100%;"src="img/Logos/instagram.png" alt=""></a></li>
                    <li><a href="https://api.whatsapp.com/send?phone=529983370624&text=" class=""><img style= " width: 70%;"src="img/Logos/Whatsapp-logo-5.png" alt=""></li>
                </ul>
            </div> <!-- End Mobile Menu Bottom -->
        </div> <!-- End Offcanvas Mobile Menu Wrapper -->
    </div> <!-- ...:::: End Offcanvas Mobile Menu Section:::... -->

    <!-- <header>

      
        <section class="wrapper">
            <input type="checkbox" id="check">
            <label class="" for="check"></label>
            <nav class="menu">
                <ul>
                    <li><a href="#">Inicio</a></li>
                    <li><a href="#">Blog</a></li>
                   
                </ul>
        </nav>
        </section>
    
        
    </header> -->

<!-- 
    <footer>
        <div style="background-color: #71D7E4; margin-bottom: 5%; text-align: center; " class="container"> 
            <h5 style="font-size:1vw; color: black; font-family: Sans-serif;"class="h5-responsive" ><img style= " width: 1.5%;"src="img/Logos/icono-llamada.png" alt=""> 998 296 1096  <img style= " width: 1.5%;"src="img/Logos/email.png" alt=""> promociones@contelexperiencias.com  <a href="https://www.facebook.com/ContelExperiencias"><img style= " width: 2%;"src="img/Logos/face.png" alt=""></a>  <a href="https://www.instagram.com/contelexperiencias/"><img style= " width: 3%;"src="img/Logos/instagram.png" alt=""></a> <a href="https://api.whatsapp.com/send?phone=529983370624&text="><img style= "width: 2%;"  src="img/Logos/Whatsapp-logo-5.png" ></a>  </h5>

        </div>
    </footer> -->
  
    
    <!-- Minified JS library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Compiled and minified Bootstrap JavaScript -->
    <script src="css/bootstrap.min.js" ></script>
    <!-- MDB -->
<script
type="text/javascript"
src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.js"
></script>
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script
type="text/javascript"
src="js/menu.js"
></script>
<script src="assets/js/jquery-3.5.1.min.js"></script>
<!-- Main JS -->
<script src="assets/js/main.js"></script>

</body>

</html>